name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_excel: ^1.0.1
  searchable_listview: ^2.14.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.5
  path_provider: ^2.0.11
  open_file: ^3.2.1


  excel: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  flutter:
  assets:
    - assets/test.xlsx
